import { type Metadata } from "next"
import { Navbar } from "@/components/marketing/navbar"
import { Footer } from "@/components/marketing/footer"

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for the Conviction platform, websites, and related services provided by Conviction AI LLC.",
}

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1">
        <article className="py-16 lg:py-24">
          <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
            <header className="mb-12">
              <h1 className="text-4xl font-semibold tracking-tight text-foreground">
                Terms of Service
              </h1>
              <p className="mt-4 text-sm text-muted-foreground">
                Effective Date: May 12, 2026
                <br />
                Last Updated: May 12, 2026
              </p>
            </header>

            <div className="prose prose-slate max-w-none">
              <section className="mb-10" id="introduction">
                <h2 className="text-2xl font-semibold text-foreground">
                  Introduction
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  These Terms of Service (&quot;Terms&quot;) govern access to
                  and use of the Conviction platform, the websites at
                  withconviction.ai and app.withconviction.ai, and any related
                  services (collectively, the &quot;Service&quot;) provided by
                  Conviction AI LLC, a Virginia limited liability company
                  (&quot;Conviction,&quot; &quot;we,&quot; &quot;our,&quot; or
                  &quot;us&quot;). By accessing or using the Service, you
                  agree to be bound by these Terms and by our Privacy Policy.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  If you are entering into these Terms on behalf of an
                  organization, you represent that you have authority to bind
                  that organization, and &quot;you,&quot; &quot;your,&quot;
                  and &quot;Customer&quot; refer to that organization. If you
                  do not agree to these Terms, do not access or use the
                  Service.
                </p>
              </section>

              <section className="mb-10" id="definitions">
                <h2 className="text-2xl font-semibold text-foreground">
                  1. Definitions
                </h2>
                <ul className="mt-4 list-disc pl-6 text-muted-foreground">
                  <li>
                    <strong className="text-foreground">&quot;Customer&quot;</strong>{" "}
                    means the organization that subscribes to the Service.
                  </li>
                  <li>
                    <strong className="text-foreground">
                      &quot;Authorized User&quot;
                    </strong>{" "}
                    or{" "}
                    <strong className="text-foreground">
                      &quot;End User&quot;
                    </strong>{" "}
                    means an individual whom Customer permits to access and use
                    the Service on Customer&apos;s behalf (e.g., an employee,
                    contractor, or analyst).
                  </li>
                  <li>
                    <strong className="text-foreground">
                      &quot;Customer Data&quot;
                    </strong>{" "}
                    means data, content, or information submitted to the
                    Service by Customer or its Authorized Users, or generated
                    through their use of the Service.
                  </li>
                  <li>
                    <strong className="text-foreground">&quot;Inputs&quot;</strong>{" "}
                    means prompts, queries, files, and other content Customer
                    or its Authorized Users submit to AI-powered features of
                    the Service.
                  </li>
                  <li>
                    <strong className="text-foreground">&quot;Output&quot;</strong>{" "}
                    means content generated by the Service, including
                    AI-generated text, summaries, scores, and reports.
                  </li>
                  <li>
                    <strong className="text-foreground">
                      &quot;Documentation&quot;
                    </strong>{" "}
                    means user guides and other materials we make available
                    describing the Service.
                  </li>
                  <li>
                    <strong className="text-foreground">
                      &quot;Order Form&quot;
                    </strong>{" "}
                    means an ordering document or online registration page
                    through which Customer subscribes to the Service.
                  </li>
                  <li>
                    <strong className="text-foreground">
                      &quot;Subscription Term&quot;
                    </strong>{" "}
                    means the term of Customer&apos;s subscription as set out
                    in the Order Form, including any renewals.
                  </li>
                </ul>
              </section>

              <section className="mb-10" id="eligibility">
                <h2 className="text-2xl font-semibold text-foreground">
                  2. Eligibility and Accounts
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  To use the Service you must be at least 18 years old and
                  capable of entering into a binding contract. You agree to
                  provide accurate information when creating an account and to
                  keep that information current. You are responsible for
                  safeguarding your account credentials and for all activities
                  that occur under your account. Notify us immediately at
                  alex@withconviction.ai of any actual or suspected
                  unauthorized access.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Customer is responsible for all activity by its Authorized
                  Users and for ensuring that each Authorized User complies
                  with these Terms.
                </p>
              </section>

              <section className="mb-10" id="subscriptions">
                <h2 className="text-2xl font-semibold text-foreground">
                  3. Subscriptions, Fees, Taxes, and Billing
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Customer may subscribe to the Service through an Order Form
                  or online registration. Fees, billing frequency, and the
                  Subscription Term are set out in the applicable Order Form or
                  registration confirmation.
                </p>
                <ul className="mt-4 list-disc pl-6 text-muted-foreground">
                  <li>
                    <strong className="text-foreground">
                      Payment processor.
                    </strong>{" "}
                    Payments are processed by Stripe. Customer authorizes
                    Conviction (and Stripe acting on our behalf) to charge the
                    payment method on file for all fees due.
                  </li>
                  <li>
                    <strong className="text-foreground">
                      Automatic renewal.
                    </strong>{" "}
                    Unless cancelled before the end of the then-current
                    Subscription Term, subscriptions renew automatically for
                    successive terms of the same length at the then-current
                    rates.
                  </li>
                  <li>
                    <strong className="text-foreground">Taxes.</strong> Fees are
                    exclusive of all taxes, levies, or duties. Customer is
                    responsible for all such amounts other than taxes
                    assessable against Conviction based on its net income.
                  </li>
                  <li>
                    <strong className="text-foreground">
                      Late and unpaid fees.
                    </strong>{" "}
                    Overdue amounts may accrue interest at the lower of 1.5%
                    per month or the maximum rate permitted by law. We may
                    suspend access for non-payment after providing notice.
                  </li>
                  <li>
                    <strong className="text-foreground">No refunds.</strong>{" "}
                    Except as expressly required by law or set out in an Order
                    Form, fees are non-refundable.
                  </li>
                </ul>
              </section>

              <section className="mb-10" id="authorized-users">
                <h2 className="text-2xl font-semibold text-foreground">
                  4. Authorized Users
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  These Terms apply to Customer and to each Authorized User.
                  Customer is responsible for ensuring its Authorized Users
                  agree to and comply with these Terms. Accounts are issued
                  per individual; sharing of accounts is prohibited.
                </p>
              </section>

              <section className="mb-10" id="acceptable-use">
                <h2 className="text-2xl font-semibold text-foreground">
                  5. Acceptable Use
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  You agree not to, and not to permit any third party to:
                </p>
                <ul className="mt-4 list-disc pl-6 text-muted-foreground">
                  <li>
                    Use the Service in violation of any applicable law or
                    regulation, including securities, anti-money-laundering,
                    and export-control laws.
                  </li>
                  <li>
                    Use the Service in connection with insider trading or the
                    trading of securities while in possession of material,
                    non-public information (&quot;MNPI&quot;) in violation of
                    applicable law.
                  </li>
                  <li>
                    Use the Service to manipulate markets or to attempt to harm
                    any third party.
                  </li>
                  <li>
                    Upload or transmit content that is unlawful, infringing,
                    defamatory, or that you do not have the right to submit.
                  </li>
                  <li>
                    Upload viruses, worms, or other malicious code, or attempt
                    to interfere with or disrupt the Service.
                  </li>
                  <li>
                    Attempt to gain unauthorized access to the Service, any
                    account other than your own, or any underlying systems or
                    networks.
                  </li>
                  <li>
                    Reverse engineer, decompile, or disassemble any part of the
                    Service except to the extent expressly permitted by
                    applicable law.
                  </li>
                  <li>
                    Use the Service for benchmarking, competitive analysis, or
                    to build a competing product.
                  </li>
                  <li>
                    Scrape, harvest, or otherwise extract data from the Service
                    except through interfaces we make available for that
                    purpose.
                  </li>
                  <li>
                    Use automated systems (e.g., bots) to access the Service
                    except as expressly authorized.
                  </li>
                  <li>
                    Redistribute, sublicense, or resell data, Output, or any
                    part of the Service.
                  </li>
                  <li>
                    Remove or obscure any copyright, trademark, or other
                    proprietary notices.
                  </li>
                </ul>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  We may, but are not obligated to, monitor use of the Service,
                  investigate violations, and remove or restrict content or
                  accounts that we reasonably believe violate these Terms.
                </p>
              </section>

              <section className="mb-10" id="customer-data">
                <h2 className="text-2xl font-semibold text-foreground">
                  6. Customer Data; Inputs and Outputs
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">Ownership.</strong> As
                  between the parties, Customer retains all right, title, and
                  interest in and to Customer Data. Customer grants Conviction
                  a worldwide, non-exclusive, royalty-free license to host,
                  copy, transmit, display, and process Customer Data and
                  Inputs solely to provide, secure, and improve the Service in
                  accordance with these Terms.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">
                    Customer responsibility.
                  </strong>{" "}
                  Customer represents and warrants that it has all rights,
                  consents, and authority necessary to provide Customer Data
                  and Inputs to the Service and that Conviction&apos;s use of
                  Customer Data as contemplated in these Terms will not
                  infringe or violate the rights of any third party or any
                  law.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">Output.</strong> Subject
                  to Customer&apos;s compliance with these Terms, Conviction
                  assigns to Customer all rights it has in Output specifically
                  generated for Customer through Customer&apos;s use of the
                  Service. Customer acknowledges that Output is not unique;
                  due to the nature of AI systems, similar Output may be
                  generated for other users. Conviction makes no claim of
                  ownership over Customer&apos;s Output but retains all rights
                  in the underlying Service.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">Aggregated data.</strong>{" "}
                  Conviction may collect and use aggregated, de-identified, or
                  anonymized data derived from use of the Service for any
                  lawful purpose, including improving the Service.
                </p>
              </section>

              <section className="mb-10" id="ai-content">
                <h2 className="text-2xl font-semibold text-foreground">
                  7. AI-Generated Content
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Some features of the Service rely on third-party AI
                  providers, including OpenAI and Google Gemini. Output
                  produced by these features:
                </p>
                <ul className="mt-4 list-disc pl-6 text-muted-foreground">
                  <li>May be inaccurate, incomplete, biased, or out of date.</li>
                  <li>Should be independently verified before being relied upon.</li>
                  <li>
                    Does not represent the views or recommendations of
                    Conviction.
                  </li>
                  <li>
                    May reflect content that is similar to Output generated
                    for other users.
                  </li>
                </ul>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Conviction does not use Customer Data to train foundation
                  models. We configure our AI integrations to disable
                  provider-side training on our API traffic where the provider
                  supports such controls.
                </p>
              </section>

              <section className="mb-10" id="third-party-integrations">
                <h2 className="text-2xl font-semibold text-foreground">
                  8. Third-Party Integrations and Services
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  The Service may integrate with third-party platforms (e.g.,
                  LinkedIn, Meta/Facebook, and market-data providers such as
                  Financial Modeling Prep). Use of those services is governed
                  by their own terms and privacy practices. You are
                  responsible for complying with applicable third-party terms
                  when you authorize a connection.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  We do not control and are not responsible for the
                  availability, accuracy, or content of third-party services,
                  and we may modify or remove integrations at any time.
                </p>
              </section>

              <section className="mb-10" id="research-disclaimer">
                <h2 className="text-2xl font-semibold text-foreground">
                  9. Investment Research Disclaimer
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  The Service provides research, analytics, and AI-generated
                  content for informational and educational purposes only. It
                  is not investment advice, financial advice, legal advice,
                  tax advice, or accounting advice, and is not a
                  recommendation to buy, sell, or hold any security or other
                  financial instrument.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Conviction AI LLC is{" "}
                  <strong className="text-foreground">not</strong> a registered
                  investment adviser, broker-dealer, or fiduciary. No
                  fiduciary, agency, or advisory relationship is created by
                  your use of the Service.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Information presented through the Service may include
                  historical data, forward-looking statements, and outputs
                  from quantitative or AI models. Past performance does not
                  guarantee future results. Backtested or hypothetical
                  performance is not indicative of actual results and is
                  subject to inherent limitations, including the benefit of
                  hindsight. You are solely responsible for your investment
                  decisions and should consult a qualified professional before
                  acting on any information.
                </p>
              </section>

              <section className="mb-10" id="ip">
                <h2 className="text-2xl font-semibold text-foreground">
                  10. Intellectual Property
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Conviction and its licensors own the Service, the
                  Documentation, all Conviction trademarks and brand assets,
                  and all software, algorithms, models, designs, and content
                  underlying the Service. Except for the limited rights
                  expressly granted in these Terms, no rights are granted to
                  you by implication, estoppel, or otherwise.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">Feedback.</strong> If you
                  provide feedback, suggestions, or recommendations regarding
                  the Service, you grant Conviction a perpetual, irrevocable,
                  royalty-free license to use that feedback without
                  restriction.
                </p>
              </section>

              <section className="mb-10" id="confidentiality">
                <h2 className="text-2xl font-semibold text-foreground">
                  11. Confidentiality
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Each party may have access to non-public information of the
                  other party that is identified as confidential or that a
                  reasonable person would understand to be confidential
                  (&quot;Confidential Information&quot;). The receiving party
                  will (a) use Confidential Information only for purposes of
                  these Terms, (b) protect it with at least the same degree of
                  care it uses for its own confidential information (and no
                  less than reasonable care), and (c) limit access to
                  personnel who need to know it for these purposes and are
                  bound by confidentiality obligations no less protective.
                  Confidential Information does not include information that
                  is or becomes publicly known without breach, is
                  independently developed without reference to the disclosing
                  party&apos;s information, or is rightfully received from a
                  third party without confidentiality obligations.
                </p>
              </section>

              <section className="mb-10" id="publicity">
                <h2 className="text-2xl font-semibold text-foreground">
                  12. Publicity
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Conviction may identify Customer by name and logo as a
                  customer of Conviction in marketing materials and on
                  Conviction&apos;s website. Customer may opt out of this use
                  by emailing alex@withconviction.ai.
                </p>
              </section>

              <section className="mb-10" id="customer-warranties">
                <h2 className="text-2xl font-semibold text-foreground">
                  13. Customer Representations and Warranties
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Customer represents and warrants that (a) it has the legal
                  authority to enter into these Terms, (b) its use of the
                  Service will comply with all applicable laws and these
                  Terms, (c) all information it provides is accurate and
                  complete, and (d) its Authorized Users will comply with
                  these Terms.
                </p>
              </section>

              <section className="mb-10" id="warranty-disclaimer">
                <h2 className="text-2xl font-semibold text-foreground">
                  14. Warranty Disclaimer
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  THE SERVICE AND ALL OUTPUT ARE PROVIDED &quot;AS IS&quot;
                  AND &quot;AS AVAILABLE,&quot; WITHOUT WARRANTIES OF ANY
                  KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. CONVICTION
                  SPECIFICALLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY,
                  FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT,
                  AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE
                  OF TRADE. CONVICTION DOES NOT WARRANT THAT THE SERVICE WILL
                  BE UNINTERRUPTED, ERROR-FREE, SECURE, OR THAT OUTPUT WILL
                  BE ACCURATE, COMPLETE, OR RELIABLE.
                </p>
              </section>

              <section className="mb-10" id="liability">
                <h2 className="text-2xl font-semibold text-foreground">
                  15. Limitation of Liability
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW:
                </p>
                <ul className="mt-4 list-disc pl-6 text-muted-foreground">
                  <li>
                    IN NO EVENT WILL CONVICTION OR ITS AFFILIATES, OFFICERS,
                    DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY
                    INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY,
                    OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE,
                    DATA, GOODWILL, BUSINESS, OR INVESTMENT LOSSES, REGARDLESS
                    OF THE THEORY OF LIABILITY AND EVEN IF ADVISED OF THE
                    POSSIBILITY OF SUCH DAMAGES.
                  </li>
                  <li>
                    CONVICTION&apos;S TOTAL AGGREGATE LIABILITY ARISING OUT OF
                    OR RELATING TO THESE TERMS OR THE SERVICE WILL NOT EXCEED
                    THE GREATER OF (A) THE FEES PAID OR PAYABLE BY CUSTOMER TO
                    CONVICTION IN THE TWELVE (12) MONTHS PRECEDING THE EVENT
                    GIVING RISE TO THE CLAIM OR (B) ONE HUNDRED U.S. DOLLARS
                    (US$100).
                  </li>
                </ul>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  These limitations form an essential basis of the bargain and
                  apply regardless of the form of action. Some jurisdictions
                  do not allow the exclusion or limitation of certain damages,
                  so some of the above may not apply to you.
                </p>
              </section>

              <section className="mb-10" id="indemnification">
                <h2 className="text-2xl font-semibold text-foreground">
                  16. Indemnification
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  You will defend, indemnify, and hold harmless Conviction and
                  its affiliates, officers, directors, employees, and agents
                  from and against any claims, damages, liabilities, costs,
                  and expenses (including reasonable attorneys&apos; fees)
                  arising out of or relating to (a) Customer Data or Inputs,
                  (b) your or your Authorized Users&apos; use of the Service
                  in violation of these Terms or applicable law, (c) any
                  investment, trading, or business decision you or any third
                  party makes in reliance on Output, or (d) your violation of
                  third-party rights.
                </p>
              </section>

              <section className="mb-10" id="termination">
                <h2 className="text-2xl font-semibold text-foreground">
                  17. Term and Termination
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  These Terms remain in effect for the duration of the
                  Subscription Term. We may suspend or terminate your access
                  to the Service, in whole or in part, if you materially
                  breach these Terms (including non-payment) and fail to cure
                  within ten (10) days after written notice, or immediately if
                  your breach involves illegal use of the Service or creates a
                  material security risk. Customer may terminate at the end of
                  the then-current Subscription Term by providing notice prior
                  to renewal.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Upon termination: (a) all rights granted to you cease; (b)
                  you must stop using the Service; (c) we may delete Customer
                  Data after a reasonable export window (generally 30 days)
                  unless retention is required by law; and (d) sections that
                  by their nature should survive termination will survive.
                </p>
              </section>

              <section className="mb-10" id="modifications-service">
                <h2 className="text-2xl font-semibold text-foreground">
                  18. Modifications to the Service
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  We may add, modify, or discontinue features of the Service
                  at any time. We will use reasonable efforts to notify
                  Customer of material adverse changes in advance.
                </p>
              </section>

              <section className="mb-10" id="beta">
                <h2 className="text-2xl font-semibold text-foreground">
                  19. Beta and Pre-Release Features
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  We may make beta or pre-release features available from time
                  to time. Such features are provided &quot;as is,&quot; may
                  be discontinued at any time, may be subject to additional
                  terms, and are not covered by any service-level commitment.
                </p>
              </section>

              <section className="mb-10" id="modifications-terms">
                <h2 className="text-2xl font-semibold text-foreground">
                  20. Modifications to These Terms
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  We may modify these Terms from time to time. We will post
                  the revised Terms on this page and update the &quot;Last
                  Updated&quot; date. If a revision is material, we will
                  provide at least 30 days&apos; notice (for example, by email
                  to Customer administrators or by an in-product notification)
                  before the revision takes effect. Continued use of the
                  Service after the effective date of revised Terms
                  constitutes acceptance of the revised Terms.
                </p>
              </section>

              <section className="mb-10" id="governing-law">
                <h2 className="text-2xl font-semibold text-foreground">
                  21. Governing Law and Venue
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  These Terms are governed by the laws of the Commonwealth of
                  Virginia, excluding its conflict-of-laws rules. Subject to
                  Section 22 (Dispute Resolution; Binding Arbitration), any
                  action that may proceed in court will be brought exclusively
                  in the state or federal courts located in Henrico County,
                  Virginia, and the parties consent to personal jurisdiction
                  and venue there.
                </p>
              </section>

              <section className="mb-10" id="arbitration">
                <h2 className="text-2xl font-semibold text-foreground">
                  22. Dispute Resolution; Binding Arbitration; Class-Action
                  Waiver
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">
                    Informal resolution.
                  </strong>{" "}
                  Before initiating a formal proceeding, the parties will
                  attempt in good faith to resolve any dispute by sending
                  written notice to the other party at the address set out in
                  Section 24 and engaging in informal negotiations for at
                  least 30 days.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">
                    Binding arbitration.
                  </strong>{" "}
                  Any dispute, claim, or controversy arising out of or
                  relating to these Terms or the Service that cannot be
                  resolved informally will be resolved by binding individual
                  arbitration administered by the American Arbitration
                  Association (&quot;AAA&quot;) under its applicable rules
                  then in effect. The arbitration will be conducted in English
                  by a single arbitrator and will take place in Richmond,
                  Virginia, or by videoconference. Judgment on the award may
                  be entered in any court of competent jurisdiction.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">
                    Class-action waiver.
                  </strong>{" "}
                  YOU AND CONVICTION AGREE THAT EACH MAY BRING CLAIMS AGAINST
                  THE OTHER ONLY IN AN INDIVIDUAL CAPACITY AND NOT AS A
                  PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS,
                  CONSOLIDATED, OR REPRESENTATIVE PROCEEDING. THE ARBITRATOR
                  MAY NOT CONSOLIDATE OR JOIN CLAIMS OF DIFFERENT PARTIES AND
                  MAY NOT PRESIDE OVER ANY FORM OF REPRESENTATIVE OR CLASS
                  PROCEEDING.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">Exceptions.</strong>{" "}
                  Either party may (a) seek injunctive or equitable relief in
                  a court of competent jurisdiction to protect
                  intellectual-property rights or confidential information, or
                  (b) bring an individual action in small-claims court for
                  claims within that court&apos;s jurisdiction.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">Opt-out.</strong>{" "}
                  Customer may opt out of this Section 22 by sending written
                  notice to alex@withconviction.ai within 30 days after first
                  accepting these Terms. The notice must include the name,
                  mailing address, and email associated with the account and a
                  clear statement that Customer is opting out of arbitration.
                  Opting out has no effect on any other provision of these
                  Terms.
                </p>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  <strong className="text-foreground">Severability.</strong>{" "}
                  If the class-action waiver is found unenforceable as to a
                  particular claim, that claim will be severed from the
                  arbitration and brought in the courts identified in Section
                  21; the remainder of this Section 22 will continue to apply.
                </p>
              </section>

              <section className="mb-10" id="export">
                <h2 className="text-2xl font-semibold text-foreground">
                  23. Export Controls; Government Use
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  You represent that you (a) are not located in any country
                  subject to comprehensive U.S. sanctions, and (b) are not on
                  any U.S. government list of restricted parties. You will not
                  use, export, or re-export the Service in violation of
                  applicable export-control or sanctions laws. If the Service
                  is licensed to a U.S. government end user, the Service is
                  &quot;commercial computer software&quot; and &quot;commercial
                  computer software documentation&quot; and is provided with
                  only those rights granted to all other end users.
                </p>
              </section>

              <section className="mb-10" id="notices">
                <h2 className="text-2xl font-semibold text-foreground">
                  24. Notices
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Notices to Conviction must be in writing and sent to
                  alex@withconviction.ai with a copy to Conviction AI LLC,
                  8401 Mayland Dr, Ste A, Richmond, VA 23294, USA. Notices to
                  Customer may be sent to the billing or administrator email
                  associated with the account or posted in the Service.
                </p>
              </section>

              <section className="mb-10" id="assignment">
                <h2 className="text-2xl font-semibold text-foreground">
                  25. Assignment
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  You may not assign these Terms, in whole or in part, without
                  our prior written consent (whether by operation of law or
                  otherwise), except to a successor in connection with a
                  merger, acquisition, or sale of substantially all of your
                  assets that is not a competitor of Conviction. Conviction
                  may assign these Terms without restriction. Any prohibited
                  assignment is void.
                </p>
              </section>

              <section className="mb-10" id="dmca">
                <h2 className="text-2xl font-semibold text-foreground">
                  26. DMCA and Copyright Complaints
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  If you believe content available through the Service
                  infringes your copyright, send a notice that complies with
                  17 U.S.C. § 512 to our designated agent at
                  alex@withconviction.ai. We may remove allegedly infringing
                  content and terminate the accounts of repeat infringers in
                  appropriate circumstances.
                </p>
              </section>

              <section className="mb-10" id="force-majeure">
                <h2 className="text-2xl font-semibold text-foreground">
                  27. Force Majeure
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Neither party will be liable for any delay or failure to
                  perform (other than payment obligations) due to causes
                  beyond its reasonable control, including acts of God, war,
                  terrorism, riots, pandemics, embargoes, acts of civil or
                  military authorities, fire, floods, accidents, network or
                  power outages, or strikes.
                </p>
              </section>

              <section className="mb-10" id="misc">
                <h2 className="text-2xl font-semibold text-foreground">
                  28. Entire Agreement; Severability; No Waiver
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  These Terms, together with the Privacy Policy and any Order
                  Form, constitute the entire agreement between the parties
                  regarding the Service and supersede any prior or
                  contemporaneous agreements on that subject. If any
                  provision is found unenforceable, that provision will be
                  modified to the minimum extent necessary to make it
                  enforceable and the rest of the Terms will remain in
                  effect. Failure to enforce any right is not a waiver of
                  that right.
                </p>
              </section>

              <section className="mb-10" id="electronic">
                <h2 className="text-2xl font-semibold text-foreground">
                  29. Headings; Counterparts; Electronic Signature
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Section headings are for convenience only. These Terms may
                  be accepted electronically, including by clicking an
                  &quot;I accept&quot; button or by using the Service.
                </p>
              </section>

              <section className="mb-10" id="survival">
                <h2 className="text-2xl font-semibold text-foreground">
                  30. Survival
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  The following sections survive termination: 6 (Customer
                  Data; Inputs and Outputs), 9 (Investment Research
                  Disclaimer), 10 (Intellectual Property), 11
                  (Confidentiality), 13 (Customer Representations and
                  Warranties), 14 (Warranty Disclaimer), 15 (Limitation of
                  Liability), 16 (Indemnification), 17 (Term and Termination),
                  21 (Governing Law and Venue), 22 (Dispute Resolution),
                  23 (Export Controls), 24 (Notices), 25 (Assignment), and
                  28–30.
                </p>
              </section>

              <section id="contact">
                <h2 className="text-2xl font-semibold text-foreground">
                  31. Contact
                </h2>
                <p className="mt-4 leading-relaxed text-muted-foreground">
                  Questions about these Terms can be directed to:
                </p>
                <address className="mt-4 not-italic leading-relaxed text-muted-foreground">
                  Conviction AI LLC
                  <br />
                  8401 Mayland Dr, Ste A
                  <br />
                  Richmond, Henrico County, VA 23294
                  <br />
                  United States
                  <br />
                  <a
                    href="mailto:alex@withconviction.ai"
                    className="font-medium text-primary hover:text-primary/80"
                  >
                    alex@withconviction.ai
                  </a>
                </address>
              </section>
            </div>
          </div>
        </article>
      </main>
      <Footer />
    </div>
  )
}
